language: python
python:
  - 3.7

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests.toolkit_tests

deploy:
  provider: pypi
  username: "pypi-AgEIcHlwaS5vcmcCJDk3YzAyM2QzLTFlODEtNGEzNi04MjY0LTNhMTIzMmFlYjFhMQACJFsxLFsic2ltcGxlZGF0YWVuZ2luZWVyaW5ndG9vbGtpdCJdXQACLFsyLFsiNmIxN2ExN2UtZWUzMi00MTkxLWFhMWQtYmE1M2ExYTdkNTUyIl1dAAAGIARWldl7y-kpCL0ky-951lw0aOxTrZCHmvKp6DWmWMKu"
  password: "$PYPI_TOKEN"
  on:
    branch: main